function [langTokens]=serializeLangTokens(lang,indent);
if ( nargin<2 || isempty(indent) ) indent=''; end;
if ( isstruct(lang) )  langTokens=lang;
elseif( iscell(lang) ) langTokens=struct(lang);
elseif ( isstr(lang) ) 
switch lang;
 case 'matlab';
  if ( isempty(indent) ) structsep=','; else structsep=[',...\n' indent]; end
  langTokens=struct('prestruct','struct(','poststruct',')','keyvalsep',',',...
                    'prekey','''','postkey','''','preval','','postval','','structsep',structsep,...
                    'prearray','[','postarray',']','arraysep',',',...
                    'prestr','''','poststr','''','strsep',',',...
                    'precell','{','postcell','}','cellsep',',',...
                    'prendmx','reshape(','prendmxdata','','postndmxdata',',',...
                    'prendmxsz','','postndmxsz','','prendmxtype','','postndmxtype','',...
                    'postndmx',')'...
                    );
  langTokens.stresc={'\','\\';'''' '\''';'"','\"'};
 case 'json';
  if ( isempty(indent) ) structsep=','; else structsep=[',\n' indent]; end;
  langTokens=struct('prestruct','{','poststruct','}','keyvalsep',':',...
                    'prekey','''','postkey','''','preval','','postval','','structsep',structsep,...
                    'prearray','[','postarray',']','arraysep',',',...
                    'prestr','''','poststr','''','strsep',',',...
                    'precell','[','postcell',']','cellsep',',',...
                    'prendmx','{data:','prendmxdata','','postndmxdata','',...
                    'prendmxsz',',size:','postndmxsz','',...
                    'prendmxtype',',type:','postndmxtype','',...
                    'postndmx','}'...
                    );
  langTokens.stresc={};
 otherwise; 
  error('Unrecognised language: %s',lang);
end;
end
return;